import ThemeToggler from '@components/ui/theme-toggler';
import Head from 'next/head';
import React from 'react';

import Sidebar from './Header/side-drawer';

import { Inter } from '@next/font/google';

interface Props {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

const MainLayout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Mahinawari</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={inter.className}>
        <Sidebar>{children}</Sidebar>
      </header>
    </>
  );
};

export default MainLayout;
